CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Methods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    CONSTRAINT "PK_Methods" PRIMARY KEY ("Id")
);

CREATE TABLE "Niveaux" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "CoursLigneGroupe" double precision NOT NULL,
    "CoursLigneIndividuel" double precision NOT NULL,
    "CoursDomicileGroupe" double precision NOT NULL,
    "CoursDomicileIndividuel" double precision NOT NULL,
    CONSTRAINT "PK_Niveaux" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Image" text NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Telephone" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Photo" text,
    "IsAdmin" boolean NOT NULL,
    "RoleId" integer NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    "Status" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Specialities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Image" text NOT NULL,
    "ServiceId" integer NOT NULL,
    CONSTRAINT "PK_Specialities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Specialities_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProfProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Cv" text NOT NULL,
    "Services" integer[] NOT NULL,
    "Specialities" integer[] NOT NULL,
    "Niveaux" integer[] NOT NULL,
    "Methodes" integer[] NOT NULL,
    CONSTRAINT "PK_ProfProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProfProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reunions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Link" text NOT NULL,
    "Description" text NOT NULL,
    "Duree" text NOT NULL,
    "Picture" text NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Reunions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reunions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StudentProfile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_StudentProfile" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentProfile_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ProfProfiles_UserId" ON "ProfProfiles" ("UserId");

CREATE INDEX "IX_Reunions_UserId" ON "Reunions" ("UserId");

CREATE INDEX "IX_Specialities_ServiceId" ON "Specialities" ("ServiceId");

CREATE INDEX "IX_StudentProfile_UserId" ON "StudentProfile" ("UserId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250514135120_addStatusAttr', '9.0.4');

COMMIT;

