CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
ALTER TABLE "Users" ALTER COLUMN "Password" DROP NOT NULL;

ALTER TABLE "ProfProfiles" ADD "City" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250523170101_cityProp', '9.0.4');

DROP TABLE "Reunions";

CREATE TABLE "Classes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Link" text NOT NULL,
    "Description" text NOT NULL,
    "Duree" text NOT NULL,
    "Picture" text NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Classes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Classes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Classes_UserId" ON "Classes" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250529110244_chnagement de nom de class reunion', '9.0.4');

COMMIT;

