
CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Telephone" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "RoleId" integer NOT NULL,
    "Photo" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProfProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL UNIQUE,
    "Cv" text NOT NULL,
    CONSTRAINT "PK_ProfProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProfProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StudentProfile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL UNIQUE,
    CONSTRAINT "PK_StudentProfile" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentProfile_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Methods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "ProfProfileId" integer,
    CONSTRAINT "PK_Methods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Methods_ProfProfiles_ProfProfileId" FOREIGN KEY ("ProfProfileId") REFERENCES "ProfProfiles" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Niveaux" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "CoursLigneGroupe" double precision NOT NULL,
    "CoursLigneIndividuel" double precision NOT NULL,
    "CoursDomicileGroupe" double precision NOT NULL,
    "CoursDomicileIndividuel" double precision NOT NULL,
    "ProfProfileId" integer,
    CONSTRAINT "PK_Niveaux" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Niveaux_ProfProfiles_ProfProfileId" FOREIGN KEY ("ProfProfileId") REFERENCES "ProfProfiles" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Image" text NOT NULL,
    "ProfProfileId" integer,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Services_ProfProfiles_ProfProfileId" FOREIGN KEY ("ProfProfileId") REFERENCES "ProfProfiles" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Specialities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Image" text NOT NULL,
    "ServiceId" integer NOT NULL,
    "ProfProfileId" integer,
    CONSTRAINT "PK_Specialities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Specialities_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Specialities_ProfProfiles_ProfProfileId" FOREIGN KEY ("ProfProfileId") REFERENCES "ProfProfiles" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Reunions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Link" text NOT NULL,
    "Description" text NOT NULL,
    "Duree" text NOT NULL,
    "Picture" text NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Reunions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reunions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
